import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { MovieProps } from "../types";

type Props = {
  popularMovies: MovieProps[];
};

const Home: NextPage<Props> = ({ popularMovies }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TOPMovies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.grid}>
        {popularMovies.map((movie: MovieProps) => (
          <div className={styles.movieCard} key={`movie-${movie.id}`}>
            <Link href={`/movies/${movie.id}`} passHref={true}>
              <div className={styles.movieImage}>
                <Image
                  src={`https://image.tmdb.org/t/p/original${movie.poster_path}`}
                  alt="Movie image"
                  layout="fill"
                  objectFit="cover"
                />
              </div>
            </Link>

            <a>{movie.title}</a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const req = await fetch(
    "https://api.themoviedb.org/3/movie/popular?api_key=4311457e3cc8a7c606a63fb963646ad1"
  );
  const { results: popularMovies } = await req.json();

  return {
    props: {
      popularMovies,
    },
  };
};
